import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { prisma } from "../db/client";

const Home: NextPage = (props: any) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-lg text-blue-500">
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p>
                    Get started by editing <code>pages/index.tsx</code>
                </p>
                <code>{props.questions}</code>
            </main>

            <footer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;

export const getServerSideProps = async () => {
    const questions = await prisma.pollQuestion.findMany();
    return {
        props: {
            questions: JSON.stringify(questions),
        },
    };
};
